### ISSUE TITLE
Running ./examples/create-user.sh throws PGP errors

### ISSUE THREAD

**Issue by precipice** [wesabe/grendel#3]
Using the 0.1.2 build, I'm seeing a big stack trace when I run the example script:

<pre><code>
localhost:examples marc$ ./create-user.sh marc testpw
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /users/ HTTP/1.1
> User-Agent: curl/7.17.1 (i386-apple-darwin9.1.0) libcurl/7.17.1 OpenSSL/0.9.8e zlib/1.2.3
> Host: localhost:8080
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
< HTTP/1.1 500 com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher
< Content-Type: text/html;charset=ISO-8859-1
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Length: 27912
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /users/. Reason:
<pre>    com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher</pre></p><h3>Caused by:</h3><pre>com.sun.jersey.api.container.MappableContainerException: com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:74)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:756)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:721)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:712)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:340)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:931)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:209)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)
Caused by: com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:122)
    at com.wesabe.grendel.resources.UsersResource.create(UsersResource.java:75)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.CGLIB$create$1(&lt;generated&gt;)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb$$FastClassByGuice$$41eb99b9.invoke(&lt;generated&gt;)
    at com.google.inject.internal.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.wideplay.warp.hibernate.HibernateLocalTxnInterceptor.invoke(HibernateLocalTxnInterceptor.java:70)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.google.inject.InterceptorStackCallback.intercept(InterceptorStackCallback.java:44)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.create(&lt;generated&gt;)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    ... 33 more
Caused by: org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:95)
    ... 48 more
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
    at javax.crypto.Cipher.getInstance(DashoA13*..)
    ... 53 more
Caused by: java.util.jar.JarException: Cannot parse file:/Users/marc/wesabe/git/grendel/target/grendel-0.1.2.jar
    at javax.crypto.SunJCE_c.a(DashoA13*..)
    at javax.crypto.SunJCE_b.b(DashoA13*..)
    at javax.crypto.SunJCE_b.a(DashoA13*..)
    ... 54 more
</pre>

<h3>Caused by:</h3><pre>com.wesabe.grendel.openpgp.CryptographicException: org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:122)
    at com.wesabe.grendel.resources.UsersResource.create(UsersResource.java:75)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.CGLIB$create$1(&lt;generated&gt;)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb$$FastClassByGuice$$41eb99b9.invoke(&lt;generated&gt;)
    at com.google.inject.internal.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.wideplay.warp.hibernate.HibernateLocalTxnInterceptor.invoke(HibernateLocalTxnInterceptor.java:70)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.google.inject.InterceptorStackCallback.intercept(InterceptorStackCallback.java:44)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.create(&lt;generated&gt;)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:756)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:721)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:712)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:340)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:931)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:209)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)
Caused by: org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:95)
    ... 48 more
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
    at javax.crypto.Cipher.getInstance(DashoA13_..)
    ... 53 more
Caused by: java.util.jar.JarException: Cannot parse file:/Users/marc/wesabe/git/grendel/target/grendel-0.1.2.jar
    at javax.crypto.SunJCE_c.a(DashoA13_..)
    at javax.crypto.SunJCE_b.b(DashoA13_..)
    at javax.crypto.SunJCE_b.a(DashoA13_..)
    ... 54 more
</pre>
<h3>Caused by:</h3><pre>org.bouncycastle.openpgp.PGPException: Exception creating cipher
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:95)
    at com.wesabe.grendel.resources.UsersResource.create(UsersResource.java:75)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.CGLIB$create$1(&lt;generated&gt;)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb$$FastClassByGuice$$41eb99b9.invoke(&lt;generated&gt;)
    at com.google.inject.internal.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.wideplay.warp.hibernate.HibernateLocalTxnInterceptor.invoke(HibernateLocalTxnInterceptor.java:70)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.google.inject.InterceptorStackCallback.intercept(InterceptorStackCallback.java:44)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.create(&lt;generated&gt;)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:756)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:721)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:712)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:340)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:931)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:209)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC
    at javax.crypto.Cipher.getInstance(DashoA13_..)
    ... 53 more
Caused by: java.util.jar.JarException: Cannot parse file:/Users/marc/wesabe/git/grendel/target/grendel-0.1.2.jar
    at javax.crypto.SunJCE_c.a(DashoA13_..)
    at javax.crypto.SunJCE_b.b(DashoA13_..)
    at javax.crypto.SunJCE_b.a(DashoA13_..)
    ... 54 more
</pre>
<h3>Caused by:</h3><pre>java.lang.SecurityException: JCE cannot authenticate the provider BC
    at javax.crypto.Cipher.getInstance(DashoA13_..)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:95)
    at com.wesabe.grendel.resources.UsersResource.create(UsersResource.java:75)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.CGLIB$create$1(&lt;generated&gt;)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb$$FastClassByGuice$$41eb99b9.invoke(&lt;generated&gt;)
    at com.google.inject.internal.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.wideplay.warp.hibernate.HibernateLocalTxnInterceptor.invoke(HibernateLocalTxnInterceptor.java:70)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.google.inject.InterceptorStackCallback.intercept(InterceptorStackCallback.java:44)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.create(&lt;generated&gt;)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:756)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:721)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:712)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:340)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:931)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:209)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)
Caused by: java.util.jar.JarException: Cannot parse file:/Users/marc/wesabe/git/grendel/target/grendel-0.1.2.jar
    at javax.crypto.SunJCE_c.a(DashoA13_..)
    at javax.crypto.SunJCE_b.b(DashoA13_..)
    at javax.crypto.SunJCE_b.a(DashoA13_..)
    ... 54 more
</pre>
<h3>Caused by:</h3><pre>java.util.jar.JarException: Cannot parse file:/Users/marc/wesabe/git/grendel/target/grendel-0.1.2.jar
    at javax.crypto.SunJCE_c.a(DashoA13_..)
    at javax.crypto.SunJCE_b.b(DashoA13_..)
    at javax.crypto.SunJCE_b.a(DashoA13_..)
    at javax.crypto.Cipher.getInstance(DashoA13_..)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at org.bouncycastle.openpgp.PGPKeyRingGenerator.&lt;init&gt;(Unknown Source)
    at com.wesabe.grendel.openpgp.KeySetGenerator.generate(KeySetGenerator.java:95)
    at com.wesabe.grendel.resources.UsersResource.create(UsersResource.java:75)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.CGLIB$create$1(&lt;generated&gt;)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb$$FastClassByGuice$$41eb99b9.invoke(&lt;generated&gt;)
    at com.google.inject.internal.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.wideplay.warp.hibernate.HibernateLocalTxnInterceptor.invoke(HibernateLocalTxnInterceptor.java:70)
    at com.google.inject.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:64)
    at com.google.inject.InterceptorStackCallback.intercept(InterceptorStackCallback.java:44)
    at com.wesabe.grendel.resources.UsersResource$$EnhancerByGuice$$9974c4eb.create(&lt;generated&gt;)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:208)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:75)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:115)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:67)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:756)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:721)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:712)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:340)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:530)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at com.wideplay.warp.persist.SessionFilter$2.run(SessionFilter.java:68)
    at com.wideplay.warp.util.Lifecycles.failEarlyAndLeaveNoOneBehind(Lifecycles.java:29)
    at com.wideplay.warp.persist.SessionFilter.doFilter(SessionFilter.java:77)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:425)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:931)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:362)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:867)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:334)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:559)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1007)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:747)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:209)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:406)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:637)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>  
<br/>                                                

</body>
</html>
- Connection #0 to host localhost left intact
- Closing connection #0
  </code></pre>

**Comment by codahale** [comment]
Fix the BC dependency issue by not repackaging it.

The Bouncy Castle JCE, upon which Grendel depends heavily, has to
be loaded from a signed JAR instead of the stripped, fat JAR built
using maven-shade-plugin. In order for that to work, the Bouncy
Castle JCE needs to be installed as a JCE provider on any systems
which will run the Grendel deployable JAR.

Instructions are provided in the README on how to do that.

(Closed by a76d8cb78ddd56b1b47efb126962c8396898f738.)

**Comment by codahale** [comment]
Fixed in a76d8cb. Thanks.
